### ISSUE TITLE
Array buffer allocation failed

### ISSUE THREAD

**Issue by septs** [amark/gun#1015]
```
2020-09-28T16:20:25.633340329Z Hello wonderful person! :) Thanks for using GUN, please ask for help on http://chat.gun.eco if anything takes you longer than 5min to figure out!
2020-09-28T16:20:25.871157091Z AXE enabled.
2020-09-28T16:20:25.881821005Z Relay peer started on port 8765 with /gun
2020-09-28T16:20:43.710747982Z Disk count not same as ram count.
2020-09-28T16:46:27.956889030Z Disk count not same as ram count.
2020-09-28T16:46:51.712915625Z buffer.js:427
2020-09-28T16:46:51.729062369Z     return createFromString(string, ops.encodingVal);
2020-09-28T16:46:51.729097098Z            ^
2020-09-28T16:46:51.729102160Z 
2020-09-28T16:46:51.729106341Z Error: Failed to allocate memory
2020-09-28T16:46:51.729110319Z     at createFromString (<anonymous>)
2020-09-28T16:46:51.729797085Z     at fromStringFast (buffer.js:427:12)
2020-09-28T16:46:51.729802762Z     at fromString (buffer.js:456:10)
2020-09-28T16:46:51.729806694Z     at Function.from (buffer.js:306:12)
2020-09-28T16:46:51.729810588Z     at writeFd (fs.js:1351:21)
2020-09-28T16:46:51.729814536Z     at fs.js:1345:7
2020-09-28T16:46:51.730371576Z     at FSReqCallback.oncomplete (fs.js:156:23) {
2020-09-28T16:46:51.730388614Z   code: 'ERR_MEMORY_ALLOCATION_FAILED'
2020-09-28T16:46:51.730392934Z }
```

```
2020-09-29T06:25:41.528550238Z Hello wonderful person! :) Thanks for using GUN, please ask for help on http://chat.gun.eco if anything takes you longer than 5min to figure out!
2020-09-29T06:25:41.755755073Z AXE enabled.
2020-09-29T06:25:41.767859659Z Relay peer started on port 8765 with /gun
2020-09-29T06:25:48.893620793Z Disk count not same as ram count.
2020-09-29T06:29:41.368388955Z Disk count not same as ram count.
2020-09-29T06:30:07.391507109Z internal/buffer.js:945
2020-09-29T06:30:07.396271180Z class FastBuffer extends Uint8Array {}
2020-09-29T06:30:07.396292758Z ^
2020-09-29T06:30:07.396297359Z 
2020-09-29T06:30:07.396301076Z RangeError: Array buffer allocation failed
2020-09-29T06:30:07.396304770Z     at new ArrayBuffer (<anonymous>)
2020-09-29T06:30:07.396998239Z     at new Uint8Array (<anonymous>)
2020-09-29T06:30:07.397003926Z     at new FastBuffer (internal/buffer.js:945:1)
2020-09-29T06:30:07.397008282Z     at createUnsafeBuffer (buffer.js:150:12)
2020-09-29T06:30:07.397012161Z     at allocate (buffer.js:420:10)
2020-09-29T06:30:07.397015975Z     at Function.allocUnsafe (buffer.js:385:10)
2020-09-29T06:30:07.397019629Z     at concat (/app/node_modules/ws/lib/buffer-util.js:17:25)
2020-09-29T06:30:07.397023703Z     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:430:21)
2020-09-29T06:30:07.397027512Z     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:367:17)
2020-09-29T06:30:07.397031147Z     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:143:22)
```

```
2020-09-29T07:02:06.389424454Z Hello wonderful person! :) Thanks for using GUN, please ask for help on http://chat.gun.eco if anything takes you longer than 5min to figure out!
2020-09-29T07:02:06.579548174Z AXE enabled.
2020-09-29T07:02:06.591699323Z Relay peer started on port 8765 with /gun
2020-09-29T07:02:15.990414655Z Disk count not same as ram count.
2020-09-29T07:08:48.311932536Z Disk count not same as ram count.
2020-09-29T07:08:48.312046348Z Disk count not same as ram count.
2020-09-29T07:09:13.932896576Z terminate called after throwing an instance of 'std::bad_alloc'
2020-09-29T07:09:14.091742655Z   what():  std::bad_alloc
```

original log file: 
[gun-logs.txt](https://github.com/amark/gun/files/5303189/gun-logs.txt)

**Comment by septs** [comment]
The platform is running in docker, use https://github.com/DimensionDev/docker-gun image.

**Comment by amark** [comment]
@septs interesting, it looks like you're able to replicate this, do you know what the data is that keeps causing it?

**Comment by septs** [comment]
if can provide a email address?

**Comment by amark** [comment]
mark@gun.eco

I'm majorly overwhelmed right now so I probably won't be able to look at this for a while - hopefully can get someone in community to help too?

If you have a lot of users on your project that helps me prioritize too. (currently dealing with some others that have 30K users/second!! :O oye!)

Also, please test against non-docker, see if it happens there still.

**Comment by septs** [comment]
We are [Maskbook](https://maskbook.com).

CC @yisiliu and @jack-works

**Comment by amark** [comment]
@septs ah yes, that means you're in-production as well with real users, and I want to make sure I keep you all afloat! :)

**Comment by septs** [comment]
radata dump is sent to you (email attachment).

**Comment by septs** [comment]
from `2020-09-28T12:38:13` to `2020-10-01T10:08:49`, crash 161 times.

about every 1.7 hour crash 1 time.

**Comment by amark** [comment]
@septs can you send me your `/stats.html` link?

**Comment by septs** [comment]
https://gun.maskbook.com/stats.html

**Comment by amark** [comment]
are you guys sending images in GUN or large data values?

... 4am here, gotta run, apologies.

**Comment by septs** [comment]
i don't know, need reply the problem @Jack-Works.

**Comment by Jack-Works** [comment]
We don't store large data in the gun, we store fix ed length crypto keys in the gun

**Comment by Tedko** [comment]
> [mark@gun.eco](mailto:mark@gun.eco)
> 
> I'm majorly overwhelmed right now so I probably won't be able to look at this for a while - hopefully can get someone in community to help too?
> 
> If you have a lot of users on your project that helps me prioritize too. (currently dealing with some others that have 30K users/second!! :O oye!)
> 
> Also, please test against non-docker, see if it happens there still.

I think we have larger users per second but not sure what’s this parameter though. Last month(mainly last week) we had 20TB data flow through gun

**Comment by Tedko** [comment]
> are you guys sending images in GUN or large data values?
> 
> ... 4am here, gotta run, apologies.

Nope. As jack said only keys

**Comment by septs** [comment]
![image](https://user-images.githubusercontent.com/3842474/95714854-6b9f5380-0c9b-11eb-9612-273b9a8653dc.png)

@amark can solve this problem? if this continues, our **costs** will be very high.

**Comment by amark** [comment]
What happens if you only run 1 relay peer? Does it reduce?

**Comment by yisiliu** [comment]
https://github.com/DimensionDev/Maskbook/blob/80a15c046434b9e27a2081aaf395e597aa12a54e/src/network/gun-servers.ts 
actually we are only using one peer now.

**Comment by yisiliu** [comment]
Do you happen to have a migration script that could help us safely migrate from v2019 to v2020 if you believe the version pump could be one of the potential problems?

**Comment by amark** [comment]
2020 should attempt to automatically upgrade data, however (1) need to use latest master (2) make a backup in case auto upgrade fails so can roll back. I'll probably be free tonight or tomorrow for a little bit of @yisiliu wants to do a screen call?

**Comment by yisiliu** [comment]
I have dumped all the traffic and I think we can go through it together during the call. Let's do it tomorrow your time, shall we?

**Comment by amark** [comment]
@yisiliu hopefully yes, I'll message you on Discord? IDK how helpful traffic is gonna be :/ but might as well try/check.

**Comment by septs** [comment]
This problem has been alleviated.

see https://github.com/DimensionDev/Maskbook/pull/1905#issuecomment-741678197
