### ISSUE TITLE
Gun throws an error by not checking a value for null

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#108]
On line 484 in gun.js, a "path" can potentially throw an error if it is null. This should be checked.

Here is the stack trace:
TypeError: Cannot read property 'join' of null at Gun.Chain.path (https://trace-awesomej.c9.io/node_modules/gun/gun.js:484:59) at Object.model.join (https://trace-awesomej.c9.io/index.js:472:23) at Gun.<anonymous> (https://trace-awesomej.c9.io/index.js:516:13) at Gun.<anonymous> (https://trace-awesomej.c9.io/node_modules/gun/gun.js:688:11) at ctx.(anonymous function) (https://trace-awesomej.c9.io/node_modules/gun/gun.js:571:10) at Chain.<anonymous> (https://trace-awesomej.c9.io/node_modules/gun/gun.js:572:8) at https://trace-awesomej.c9.io/node_modules/gun/gun.js:317:80

**Comment by PsychoLlama** [comment]
@metasean here is the minimum code needed to replicate the error:
Gun().path(null)

No other falsy values seem to cause this problem.
