### ISSUE TITLE
On update, examples may still reference previous version of gun

### ISSUE THREAD

**Issue by metasean** [amark/gun#111]
ERROR:

```
> gun@0.2.3 start /Volumes/Macintosh HD/Users/username/projects/gun-demo/gun
> node examples/http.js 8080

/Volumes/Macintosh HD/Users/username/projects/gun-demo/gun/examples/http.js:22
gun.attach(server);
    ^
TypeError: undefined is not a function
    at Object.<anonymous> (/Volumes/Macintosh HD/Users/username/projects/gun-demo/gun/examples/http.js:22:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

npm ERR! Darwin 10.8.0
npm ERR! argv "node" "/Users/name/.nvm/versions/node/v0.12.0/bin/npm" "start"
npm ERR! node v0.12.0
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! gun@0.2.3 start: `node examples/http.js 8080`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gun@0.2.3 start script 'node examples/http.js 8080'.
npm ERR! This is most likely a problem with the gun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node examples/http.js 8080
npm ERR! You can get their info via:
npm ERR!     npm owner ls gun
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Volumes/Macintosh HD/Users/username/projects/gun-demo/gun/npm-debug.log
```

**Comment by amark** [comment]
This wound up being more of a NPM problem... still had a pain with it until recently but seems with everybody else that it is no longer problematic. Gonna close!
