### ISSUE TITLE
crash with escaped characters on put method

### ISSUE THREAD

**Issue by oenzoferrari** [amark/gun#1182]
How to reproduce:

```js
gun.get('any_location').put({
  content: '\\\\',
});
```

Output:

```js
undefined:1
"\\"}},"
    ^

SyntaxError: Unexpected token } in JSON at position 4
    at JSON.parse (<anonymous>)
    at parse ($PROJECT_PATH/node_modules/gun/lib/yson.js:33:51)
    at yson.parseAsync ($PROJECT_PATH/node_modules/gun/lib/yson.js:12:2)
    at Function.Mesh.mesh.hear ($PROJECT_PATH/node_modules/gun/gun.js:1375:6)
    at WebSocket.<anonymous> ($PROJECT_PATH/node_modules/gun/lib/wire.js:75:13)
    at WebSocket.emit (node:events:390:28)
    at Receiver.receiverOnMessage ($PROJECT_PATH/node_modules/ws/lib/websocket.js:1008:20)
    at Receiver.emit (node:events:390:28)
    at Receiver.dataMessage ($PROJECT_PATH/node_modules/ws/lib/receiver.js:517:14)
    at Receiver.getData ($PROJECT_PATH/node_modules/ws/lib/receiver.js:435:17)
```

**Comment by amark** [comment]
Hey @oenzoferrari , sorry, this was a stupid/bad bug when I migrated things, its actually been fixed for a long time on GitHub main, I've been bad about not publishing to NPM. Can you try main? Fix should be confirmed. :) Closing until then, thanks for the reminder tho!
