### ISSUE TITLE
Uncaught TypeError: Cannot create property '' on number '1626387020485.1992'

### ISSUE THREAD

**Issue by mmalmi** [amark/gun#1256]
Happens on Iris messenger sometimes:

```
Uncaught TypeError: Cannot create property '' on number '1626387020485.1992'
    at e (radix.js:70:36)
    at e (radix.js:101:11)
    at e (radix.js:101:11)
    at e (radix.js:101:11)
    at e (radix.js:101:11)
    at e (radix.js:101:11)
    at e (radix.js:101:11)
    at e (radix.js:101:11)
    at e (radix.js:101:11)
    at e (radix.js:101:11)
```

<img width="542" alt="Screenshot 2022-06-19 at 16 00 47" src="https://user-images.githubusercontent.com/2116445/174482302-24e46ab8-df90-445e-992d-3eb812504da0.png">
<img width="730" alt="Screenshot 2022-06-19 at 16 01 11" src="https://user-images.githubusercontent.com/2116445/174482304-0e9d4348-99b8-4f57-8177-85709827c2ff.png">

**Comment by mmalmi** [comment]
The error comes from radix.js which is from gun.

**Comment by draeder** [comment]
Oh, right.. I don't know how I missed the screenshot full of red text LOL. Either way, you may still want to post in Iris. It could be an issue there that is causing radix to error out.
