### ISSUE TITLE
setTimeout.each is not a function

### ISSUE THREAD

**Issue by KrzysztofZawisla** [amark/gun#1289]
I started getting error as in title. 

gun,js:1611
at t.hi (gun.js:1611:16)
at r.onopen (gun.js:1703:15)

Any idea how to fix that?

**Comment by amark** [comment]
Can you put up a https://jsbin.com/ example?

**Comment by D-Mino** [comment]
Same error.

gun = new Gun();
user = gun.user(); 
user.create(alias, pass, cb, opt); => throw error

**Comment by imizaac** [comment]
https://jsbin.com/quropiduki/edit?html,console

This contains all your cited code @quoctran18 do you have more? In your case what is `alias`, `pass`, `cb`, and `opt`?
