### ISSUE TITLE
0.5: `.path` fails to load circular nested primitives

### ISSUE THREAD

**Issue by PsychoLlama** [amark/gun#295]
When working with circular references, sometimes `.path` never loads primitive values.
Oddly enough, I can't reproduce the issue with document-structured data, so my assumption is that it's related to circular structures.

```js
// Save two people.
bob = gun.get('bob').put({ name: 'Bob' })
dave = gun.get('dave').put({ name: 'Dave' })

// Link them to each other.
bob.path('friend').put(dave)
dave.path('friend').put(bob)

// Prints "Dave".
bob.path('friend.name').val(console.log)

// Prints Bob's object, including "name" property.
bob.path('friend.friend').val(console.log)

// Nothing happens.
bob.path('friend.friend.name').val(console.log)
```

If `.val` is replaced with `.any`, it fires with the `Bob` object (which contains `name`), but nothing further happens.

**UPDATE**
Once the browser is refreshed, and it reads the data from `localStorage`, gun is able to print `friend.friend.name`. So this might be related to how items on the chain are cached?

**Comment by amark** [comment]
Thanks, will make sure to add this to tests and have it fixed.

**Comment by d3x0r** [comment]
hmm... this is similar... gun fails to save circular nested things...

```
/* let's define an appropriate deep default database... */
var dflt = {
	1: { 
		name : "org1",
		sites : { 
			1: { 
				name : "site1",
				users : {
					1: {
						name: "alice",
						boss : {}, // ** referenced later to betty; as an object
						siblings : { 
							mark : {} // ** see users org3, site 5
						}
					},
					2: { 
						name: "betty"
					}
				}
			},
			2: {
				name : "site2",
				users : { 
					1 : { 
						name : "charlie",
						boss : {} // ** referenced later to david }
					},
					2: { 
						name : "david"
					}
				}
			},
		}
	},
	3: {
		name : "org3",
		sites : {
			5: {
				name : "site5",
				users : {
					1 : {
						name : "edward"
					},
					2 : {
						name : "frank"
					},
					3 : {
						name : "mark"
					}
				}
			},
			7: {
				name : "site7",
				users : {
					1 : {
						name : "georgia"
					},
					2 : {
						name : "hank"
					}
				}
			}
		}
	}
}

/*
// these relations also exist.
dflt[1].sites[1].users[1].boss = dflt[1].sites[1].users[2];
dflt[1].sites[1].users[1].siblings.mark = dflt[3].sites[5].users[3];
dflt[1].sites[2].users[1].boss = dflt[1].sites[2].users[2];
*/


var Gun = require( "gun" );
var gun = Gun();

gun.get( "root" );
console.log( "got root..." );
gun.put( dflt );
console.log( "put default data..." );

var bossref = gun.get( "root" ).path( "1.sites.1.users.2" );
console.log( "got a ref?" );
gun.get( "root" ).path( "1.sites.1.users.1.boss" ).put( bossref );
console.log( "put the ref out?" );
```

```
	...node_modules\gun\gun.js:104
                        return !o? o : JSON.parse(JSON.stringify(o)); // is shockingly faster than anything else, and ou
r data has to be a subset of JSON anyways!
                                                       ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Type.obj.copy (...node_modules\gun\gun.js:104:35)
    at Object.map (...node_modules\gun\gun.js:663:19)
    at Object.Node.ify (...node_modules\gun\gun.js:516:31)
    at node (...node_modules\gun\gun.js:647:13)
    at Object.map (...node_modules\gun\gun.js:683:11)
    at Object.map (...node_modules\gun\gun.js:524:18)
    at Type.obj.map (...node_modules\gun\gun.js:137:19)
    at Object.Node.ify (...node_modules\gun\gun.js:518:6)
    at node (...node_modules\gun\gun.js:647:13)
```

**Comment by amark** [comment]
@d3x0r just to confirm, this still crashes under `0.5.5` ? It looks like it is behaving as `0.5.3` before I fixed a few things.

**Comment by amark** [comment]
RE: Original issue. This works now under 0.6.2+ ! http://jsbin.com/zihodumowe/edit?js,console . It should nice also work for your case, @d3x0r . Gonna close, although if you are still having problems please reopen.
