### ISSUE TITLE
Multi-instance Ask/Ack are Shared Globally

### ISSUE THREAD

**Issue by d3x0r** [amark/gun#326]
```

var Gun = require( "../" );

var a = Gun( { file: "a.json" } );
var b = Gun( { file : "b.json" } );
var c = Gun( { file : "c.json" } );
var d = null;
Gun.on('out', function(msg){
	var onGun = msg.gun.back(-1);
	if( onGun === a ) {
		console.log( "a sends to b...." );
		b.on( "in", msg );
	}
	else if( onGun === b ) {
		console.log( "b sends to a...." );
		a.on( "in", msg );
		if(d) {
			console.log( "b can also send to d...." );
			 d.on( "in", msg );
		}
	}
	else if( onGun === c ) {
		console.log( "c sends to noone..." );
	}
	else if( onGun === d ) {
		console.log( "d sends to b...." );
		b.on( "in", msg );
	}

	else   console.log( ["to where?...", JSON.stringify(onGun), "\n Message:", JSON.stringify(msg)].join(" ") );
		this.to.next(msg)
})

var ab = a.get( "key" );
var bb = b.get( "key" );
ab.map( (val,field)=>{console.log("a key got val:", field, val ) } );
bb.map( (val,field)=>{console.log("b key got val:", field, val ) } );
bb.put( { msg: "hello"} );

setTimeout( ()=>{
	console.log( "tick" );
	var cb = c.get( "key" );
	cb.map( (val,field)=>{console.log("c key got val:", field, val ) } );
	bb.map( (val,field)=>{console.log("b2 key got val:", field, val ) } );
	
	d = Gun( { file : "d.json" } );
	var db = d.get("key");
	db.map( (val,field)=>{console.log("d key got val:", field, val ) } );
	
}, 1000 );

```
A is an independant instance
B is an independant instance
C is an independant instance
D is an inepdendant instance that is opened much later after all puts are done

A and B send to each other
C does not  talk to anyone (check for file driver data bleed)
D and B talk to each other, but only if D exists (because it is later opened)

A and B simulate a client that is connected during all time the server has data....
D simulates a client connecting to a server after some point
 
What is expected that doesn't happen....
   a.json gets no data
   d.json gets no data
   map on d("key") gets nothing; and should get the data from the 'server'  b.

**Comment by amark** [comment]
quick note (like I mentioned on gitter), the new event system requires you manually call next `this.to.next(msg)` or else the other drivers (like file.js / data.json) won't get called.

**Comment by amark** [comment]
^ that log sounds like everything is working EXCEPT for files being written. But if you added:

```
Gun.on('out', function(msg){
  this.to.next(msg)
```

Then it should (well as long as the file drivers are attached which I assume they are). If everything else is working (except storage) the storage should work, so this seems like it might be a wiring problem, but let's assume it is a bug, and I'll check on it. Have to prioritize gun client/paid work first though, have deadlines soon.

**Comment by amark** [comment]
oh apparently D still isn't getting called... yeah will check in on this later.

**Comment by d3x0r** [comment]
```
var Gun = require( "../" );

var b = Gun( { file : "b.json" } );
var d = null;

Gun.on('out', function(msg){
	var onGun = msg.gun.back(-1);
	if( onGun === b ) {
		if(d) {
			console.log( "b can send to d...." );
			 d.on( "in", msg );
		}
	} else if( onGun === d ) {
		console.log( "d sends to b...." );
		b.on( "in", msg );
	}
	this.to.next(msg)
})

var bb = b.get( "key" );
bb.put( { msg: "hello"} );
	
d = Gun( { file : "d.json" } );
var db = d.get("key");
db.map( (val,field)=>{console.log("d key got val:", field, val ) } );

```
Here; no timeout, no extra gun instances, just b that puts something in himself and d.
Doesn't seem to matter to clear b.json or not.
Probably it would fail in a browser too?

**Comment by d3x0r** [comment]
with Gun.on moved up, and added 'mtos' method to show messages more how websock sends  them... and capturing a log between for the above sample....
```
b wanted to send to someone? {"put":{"key":{"_":{"#":"key",">":{"msg":1488506761279}},"msg":"hello"}},"#":"6LieLj7BHoe63bXFHeyaFAc0"}
b wanted to send to someone? {"put":{"key":{"_":{"#":"key",">":{"msg":1488506761279}},"msg":"hello"}},"#":"6LieLj7BHoe63bXFHeyaFAc0"}
b wanted to send to someone? {"get":{"#":"key",".":"_"},"#":"VvtfwAeTAcJ0F7VWNxpW6pAX"}
b wanted to send to someone? {"get":{"#":"key",".":"_"},"#":"VvtfwAeTAcJ0F7VWNxpW6pAX"}
Map functions are experimental, their behavior and API may change moving forward. Please play with it and report bugs and ideas on how to improve it.
d sends to b.... {"get":{"#":"key"},"#":"4Bu5OxUtm64gwQ9dTypiV8El"}
d sends to b.... {"get":{"#":"key"},"#":"4Bu5OxUtm64gwQ9dTypiV8El"}
d sends to b.... {"get":{"#":"key"},"#":"4Bu5OxUtm64gwQ9dTypiV8El"}

```

And The websock messages similarly..... that's the chat app, with no data in the server, and the client connects and sends a message... (generates a put)  The put message sent to gun from a client includes a LOT more information than the one that is passed internally.
```
input: {"headers":{"gun-sid":"KDht5SGuK0"},"body":{"get":{"#":"example/chat/data"},"#":"4pQiXU4TzPdq2vedvgSDvpkS"}}
output: {"headers":{},"body":{"@":"4pQiXU4TzPdq2vedvgSDvpkS","#":"iM99NeS0Oh0GhGLMQxce062s"}}
output: {"headers":{},"body":{"get":{"#":"example/chat/data"},"#":"4pQiXU4TzPdq2vedvgSDvpkS"}}
input: {"headers":{"gun-sid":"KDht5SGuK0"},"body":{"get":{"#":"example/chat/data"},"#":"4pQiXU4TzPdq2vedvgSDvpkS"}}
input: {"headers":{"gun-sid":"KDht5SGuK0"},"body":{"get":{"#":"BeVCxD1qQnocQinoqD1Pg0th"},"#":"gAdB3DykQy1ihqAFNIqQGU48"}}
output: {"headers":{},"body":{"@":"gAdB3DykQy1ihqAFNIqQGU48","#":"otyu0jbitTOaVOzkwp41rsPL"}}
output: {"headers":{},"body":{"get":{"#":"BeVCxD1qQnocQinoqD1Pg0th"},"#":"gAdB3DykQy1ihqAFNIqQGU48"}}
input: {"headers":{"gun-sid":"KDht5SGuK0"},"body":{"get":{"#":"BeVCxD1qQnocQinoqD1Pg0th"},"#":"gAdB3DykQy1ihqAFNIqQGU48"}}
input: {"headers":{"gun-sid":"KDht5SGuK0"},"body":{"put":{"BeVCxD1qQnocQinoqD1Pg0th":{"_":{"#":"BeVCxD1qQnocQinoqD1Pg0th",">":{"when":1488502667873,"who":1488502667873,"what":1488502667873}},"when":1488502667872,"who":"asdf","what":"asdfasdf"},"example/chat/data":{"_":{"#":"example/chat/data",">":{"1488502667872_aTDQ":1488502667873}},"1488502667872_aTDQ":{"#":"BeVCxD1qQnocQinoqD1Pg0th"}}},"#":"hNxMz0kC8hdU6E3yl4jzMcJR"}}
output: {"headers":{},"body":{"put":{"BeVCxD1qQnocQinoqD1Pg0th":{"_":{"#":"BeVCxD1qQnocQinoqD1Pg0th",">":{"when":1488502667873,"who":1488502667873,"what":1488502667873}},"when":1488502667872,"who":"asdf","what":"asdfasdf"},"example/chat/data":{"_":{"#":"example/chat/data",">":{"1488502667872_aTDQ":1488502667873}},"1488502667872_aTDQ":{"#":"BeVCxD1qQnocQinoqD1Pg0th"}}},"#":"hNxMz0kC8hdU6E3yl4jzMcJR"}}
input: {"headers":{"gun-sid":"KDht5SGuK0"},"body":{"put":{"BeVCxD1qQnocQinoqD1Pg0th":{"_":{"#":"BeVCxD1qQnocQinoqD1Pg0th",">":{"when":1488502667873,"who":1488502667873,"what":1488502667873}},"when":1488502667872,"who":"asdf","what":"asdfasdf"},"example/chat/data":{"_":{"#":"example/chat/data",">":{"1488502667872_aTDQ":1488502667873}},"1488502667872_aTDQ":{"#":"BeVCxD1qQnocQinoqD1Pg0th"}}},"#":"hNxMz0kC8hdU6E3yl4jzMcJR"}}
output: {"headers":{},"body":{"@":"hNxMz0kC8hdU6E3yl4jzMcJR","ok":1,"err":null,"#":"Hvfzl4eyN3L47nogFMbuAQEB"}}
```

**Comment by amark** [comment]
@d3x0r figured it out 
there is an internal in-memory acknowledgement system

d3x0r @d3x0r 19:17
cheers

Mark Nadal @amark 19:17
annnnnd, like you found with the deduplication system
it was global, not per-instance.

d3x0r @d3x0r 19:18
ahh hah 

Mark Nadal @amark 19:18
so it was routing it directly back (since that is more efficient to do)

d3x0r @d3x0r 19:18
see - simple fix 

Mark Nadal @amark 19:18
rather than letting it out
yupe

**Comment by amark** [comment]
fix to come.

**Comment by d3x0r** [comment]
did you push fix this?
Because... I'm getting writes on game mesh that are triggered to writes on auth mesh ... which are in entirely separate branches anyway...

**Comment by d3x0r** [comment]
```
gun put dbRecord: { '532':
   { '90':
      { time: '"2017-03-07T02:24:41.586Z"',
        gameTime: '"2017-03-07T02:09:00.000Z"',
        gameNumber: 532,
        pack: 90,
        cards: '[{"id":36535,"face":[[2,null,null,32,null,58,null,76,80],[null,null,22,39,43,null,62,null,84],[5,15,23,null,46,null,66]]},{"id":36536,"face":[[6,null,20,31,40,null,null,70],[null,12,null,null,48,50,69,null,81],[null,null,null,36,49,56,null,78,83]]},{"id":36537,"face":[[8,null,null,33,null,53,60,71],[null,16,24,null,47,55,null,null,86],[null,17,28,null,null,59,67,79]]},{"id":36538,"face":[[4,13,null,null,null,54,null,72,89],[null,19,null,30,42,null,63,77],[7,null,29,37,44,null,null,null,90]]},{"id":36539,"face":[[null,10,21,34,null,null,null,74,82],[3,11,null,null,45,51,null,null,88],[null,null,27,35,null,57,68,75]]},{"id":36540,"face":[[1,null,25,38,null,null,61,null,85],[9,14,26,null,null,52,64],[null,18,null,null,41,null,65,73,87]]}]' } } }
sending sales gun message: {"headers":{},"body":{"get":{"#":"l34JEuUPARtOscUSpXlMlNso",".":"90"},"#":"V2dkSIFKmH0Mi2O9dAR2ITX6"}}
Send to sales gun peers...
sending sales gun message: {"headers":{},"body":{"get":{"#":"l34JEuUPARtOscUSpXlMlNso",".":"90"},"#":"V2dkSIFKmH0Mi2O9dAR2ITX6"}}
Send to sales gun peers...
sales90 : event from self put? 532 { '83': { '#': 'bioS5G7rcKXBzCqetrNBTyos' },
  '84': { '#': 'LW8seLebarIVuFLFw6GnoG1A' },
  '85': { '#': 'e95rHnJlfomzx5uwMgx3uf8V' },
  '86': { '#': 'mmaBmBvKJ8crWD9mQPBMqCFa' },
  '87': { '#': '7aUvuMSBzVDlDXzhP3UpryWH' },
  '88': { '#': 'Fk1XCJBAhf5p6eL8NDlsLwvA' },
  '89': { '#': 'SsFEOnEvPNiRT38879qjceGQ' },
  '90': { '#': 'TIrWM3UwW4ILw72D91QnvmMy' },
  _:
   { '>':
      { '83': 1488853024751,
        '84': 1488853119432,
        '85': 1488853157637,
        '86': 1488853188125,
        '87': 1488853353666,
        '88': 1488853363805,
        '89': 1488853469451,
        '90': 1488853481587 },
     '#': 'l34JEuUPARtOscUSpXlMlNso' } }
sending sales gun message: {"headers":{},"body":{"get":{"#":"TIrWM3UwW4ILw72D91QnvmMy",".":"_"},"#":"SKta1r00fh8c7h8Rwqs9zJMz"}}
Send to sales gun peers...
sending sales gun message: {"headers":{},"body":{"get":{"#":"TIrWM3UwW4ILw72D91QnvmMy",".":"_"},"#":"SKta1r00fh8c7h8Rwqs9zJMz"}}
Send to sales gun peers...
sales90 : event from self put? 532 { '83': { '#': 'bioS5G7rcKXBzCqetrNBTyos' },
  '84': { '#': 'LW8seLebarIVuFLFw6GnoG1A' },
  '85': { '#': 'e95rHnJlfomzx5uwMgx3uf8V' },
  '86': { '#': 'mmaBmBvKJ8crWD9mQPBMqCFa' },
  '87': { '#': '7aUvuMSBzVDlDXzhP3UpryWH' },
  '88': { '#': 'Fk1XCJBAhf5p6eL8NDlsLwvA' },
  '89': { '#': 'SsFEOnEvPNiRT38879qjceGQ' },
  '90': { '#': 'TIrWM3UwW4ILw72D91QnvmMy' },
  _:
   { '>':
      { '83': 1488853024751,
        '84': 1488853119432,
        '85': 1488853157637,
        '86': 1488853188125,
        '87': 1488853353666,
        '88': 1488853363805,
        '89': 1488853469451,
        '90': 1488853481587 },
     '#': 'l34JEuUPARtOscUSpXlMlNso' } }
sending sales gun message: {"headers":{},"body":{"put":{"TIrWM3UwW4ILw72D91QnvmMy":{"_":{"#":"TIrWM3UwW4ILw72D91QnvmMy",">":{"time":1488853481587,"gameTime":1488853481587,"gameNumber":1488853481587,"pack":1488853481587,"cards":1488853481587}},"time":"\"2017-03-07T02:24:41.586Z\"","gameTime":"\"2017-03-07T02:09:00.000Z\"","gameNumber":532,"pack":90,"cards":"[{\"id\":36535,\"face\":[[2,null,null,32,null,58,null,76,80],[null,null,22,39,43,null,62,null,84],[5,15,23,null,46,null,66]]},{\"id\":36536,\"face\":[[6,null,20,31,40,null,null,70],[null,12,null,null,48,50,69,null,81],[null,null,null,36,49,56,null,78,83]]},{\"id\":36537,\"face\":[[8,null,null,33,null,53,60,71],[null,16,24,null,47,55,null,null,86],[null,17,28,null,null,59,67,79]]},{\"id\":36538,\"face\":[[4,13,null,null,null,54,null,72,89],[null,19,null,30,42,null,63,77],[7,null,29,37,44,null,null,null,90]]},{\"id\":36539,\"face\":[[null,10,21,34,null,null,null,74,82],[3,11,null,null,45,51,null,null,88],[null,null,27,35,null,57,68,75]]},{\"id\":36540,\"face\":[[1,null,25,38,null,null,61,null,85],[9,14,26,null,null,52,64],[null,18,null,null,41,null,65,73,87]]}]"},"l34JEuUPARtOscUSpXlMlNso":{"90":{"#":"TIrWM3UwW4ILw72D91QnvmMy"},"_":{"#":"l34JEuUPARtOscUSpXlMlNso",">":{"90":1488853481587}}},"purchases":{"532":{"#":"l34JEuUPARtOscUSpXlMlNso"},"_":{"#":"purchases",">":{"532":1488853481587}}}},"#":"O0OG9GTteSrG0ItaIUdgXRJC"}}
Send to sales gun peers...
sending sales gun message: {"headers":{},"body":{"put":{"TIrWM3UwW4ILw72D91QnvmMy":{"_":{"#":"TIrWM3UwW4ILw72D91QnvmMy",">":{"time":1488853481587,"gameTime":1488853481587,"gameNumber":1488853481587,"pack":1488853481587,"cards":1488853481587}},"time":"\"2017-03-07T02:24:41.586Z\"","gameTime":"\"2017-03-07T02:09:00.000Z\"","gameNumber":532,"pack":90,"cards":"[{\"id\":36535,\"face\":[[2,null,null,32,null,58,null,76,80],[null,null,22,39,43,null,62,null,84],[5,15,23,null,46,null,66]]},{\"id\":36536,\"face\":[[6,null,20,31,40,null,null,70],[null,12,null,null,48,50,69,null,81],[null,null,null,36,49,56,null,78,83]]},{\"id\":36537,\"face\":[[8,null,null,33,null,53,60,71],[null,16,24,null,47,55,null,null,86],[null,17,28,null,null,59,67,79]]},{\"id\":36538,\"face\":[[4,13,null,null,null,54,null,72,89],[null,19,null,30,42,null,63,77],[7,null,29,37,44,null,null,null,90]]},{\"id\":36539,\"face\":[[null,10,21,34,null,null,null,74,82],[3,11,null,null,45,51,null,null,88],[null,null,27,35,null,57,68,75]]},{\"id\":36540,\"face\":[[1,null,25,38,null,null,61,null,85],[9,14,26,null,null,52,64],[null,18,null,null,41,null,65,73,87]]}]"},"l34JEuUPARtOscUSpXlMlNso":{"90":{"#":"TIrWM3UwW4ILw72D91QnvmMy"},"_":{"#":"l34JEuUPARtOscUSpXlMlNso",">":{"90":1488853481587}}},"purchases":{"532":{"#":"l34JEuUPARtOscUSpXlMlNso"},"_":{"#":"purchases",">":{"532":1488853481587}}}},"#":"O0OG9GTteSrG0ItaIUdgXRJC"}}
Send to sales gun peers...
sending game gun message: {"headers":{},"body":{"get":{"#":"l34JEuUPARtOscUSpXlMlNso",".":"90"},"#":"V2dkSIFKmH0Mi2O9dAR2ITX6"}}
```

The below I think should not be happening..... I double checked that I'm not falsely sending becauase of a missed else or something.... and it's really coming from gun...

each mesh is new Gun().get( "gameState" ) and newGun.get( "purchases" )
Where purches will be a enumerated transaction list 1,2,3,4,5, contianing receipts... that contain the data... 
so any put on purchases should never be felt on gamestate, because it's a different root and there should never be a 90 in 'gameState' 
```
Trace: Send to game gun peers...
    at sendGameGun (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\http2.js:85:25)
    at Object.sendGun [as next] (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\http2.js:39:9)
    at Object.next (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\lib\wsp\client.js:49:10)
    at Function.onto [as on] (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\gun.js:197:19)
    at Object.input [as next] (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\gun.js:896:9)
    at Object.onto [as on] (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\gun.js:197:19)
    at Gun.chain.on (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\gun.js:1852:14)
    at WebSocketConnection.connection.on (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\http2.js:395:21)
    at emitOne (events.js:96:13)
    at WebSocketConnection.emit (events.js:188:7)
sending game gun message: {"headers":{},"body":{"get":{"#":"TIrWM3UwW4ILw72D91QnvmMy",".":"_"},"#":"SKta1r00fh8c7h8Rwqs9zJMz"}}
Trace: Send to game gun peers...
    at sendGameGun (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\http2.js:85:25)
    at Object.sendGun [as next] (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\http2.js:39:9)
    at Object.next (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\lib\wsp\client.js:49:10)
    at Function.onto [as on] (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\gun.js:197:19)
    at Object.input [as next] (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\gun.js:896:9)
    at Object.onto [as on] (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\gun.js:197:19)
    at Gun.chain.on (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\node_modules\gun\gun.js:1852:14)
    at WebSocketConnection.connection.on (M:\eqube\Vegas\trunk\javascript\eqube\linkedGame2\server\http2.js:395:21)
    at emitOne (events.js:96:13)
    at WebSocketConnection.emit (events.js:188:7)
receive on gamestate { type: 'utf8',
  utf8Data: '{"headers":{},"body":{"@":"V2dkSIFKmH0Mi2O9dAR2ITX6","#":"aCcTkLfI0rRNpLvtroBROHg4"}}' }
receive on gamestate { type: 'utf8',
  utf8Data: '{"headers":{},"body":{"get":{"#":"l34JEuUPARtOscUSpXlMlNso",".":"90"},"#":"V2dkSIFKmH0Mi2O9dAR2ITX6"}}' }
receive on gamestate { type: 'utf8',
  utf8Data: '{"headers":{},"body":{"@":"V2dkSIFKmH0Mi2O9dAR2ITX6","#":"qisFSEsJPkxBSJalMjauaEMR"}}' }
receive on gamestate { type: 'utf8',
  utf8Data: '{"headers":{},"body":{"get":{"#":"l34JEuUPARtOscUSpXlMlNso",".":"90"},"#":"V2dkSIFKmH0Mi2O9dAR2ITX6"}}' }
receive on gamestate { type: 'utf8',
  utf8Data: '{"headers":{},"body":{"@":"SKta1r00fh8c7h8Rwqs9zJMz","#":"9Ual73kPBTI1Rm7nlhXLU6PQ"}}' }
receive on gamestate { type: 'utf8',
  utf8Data: '{"headers":{},"body":{"@":"SKta1r00fh8c7h8Rwqs9zJMz","#":"FyQzyvTboEWiXtczfd7xOxvc"}}' }
receive on gamestate { type: 'utf8',
  utf8Data: '{"headers":{},"body":{"get":{"#":"TIrWM3UwW4ILw72D91QnvmMy",".":"_"},"#":"SKta1r00fh8c7h8Rwqs9zJMz"}}' }
receive on gamestate { type: 'utf8',
  utf8Data: '{"headers":{},"body":{"get":{"#":"TIrWM3UwW4ILw72D91QnvmMy",".":"_"},"#":"SKta1r00fh8c7h8Rwqs9zJMz"}}' }
Mon Mar 06 2017 18:25:11 GMT-0800 (Pacific Standard Time) GUN Peer ::ffff:127.0.0.1 disconnected.
Mon Mar 06 2017 18:25:23 GMT-0800 (Pacific Standard Time) Peer ::ffff:127.0.0.1 disconnected.
```

**Comment by amark** [comment]
:( no I haven't pushed it yet :( I'm trying to bundle it in with the other driver/adapter updates that are now doing 625 inserts/second (or 1,785 inserts/second without storage / storage acks). But I got some stinking unit tests that are broken I am trying to fix.

**Comment by amark** [comment]
I have a full fix (many lines). However 1 line causes the chat example to not work. So I'm gonna push what I have (without the 1 line that breaks the chat example) and we can follow up on how to combine the two without breaking the chat app.

**Comment by amark** [comment]
comment out this line: https://github.com/amark/gun/blob/master/gun.js#L861 and uncomment the line beneath it (that is currently commented)

**Comment by d3x0r** [comment]
I was running my test and I don't have issues with that line in place.....
(and it didn't change the behavior on the websocket driven example) 
I'll go ahead and close this since it is passing the full test (a,b,c,d) with ( a-b   c   b-d  ) and events that happened before D connects are received by D and changes made after D connects ARE received by D.  (not in my sockets right now; so probably still and issue like I have a Gun.on too late)
