### ISSUE TITLE
Gun doesn't work in node-to-node setup

### ISSUE THREAD

**Issue by sergibondarenko** [amark/gun#422]
node 6.11.1
gun 0.8.5

I get no response from Gun server.

Client code, [this](https://github.com/amark/gun/wiki/graphs) example:
```
const Gun = require('gun');

const gun = Gun('http://localhost:8080/gun');

const alice = gun.get('person/alice').put({name: 'alice', age: 22});
const bob = gun.get('person/bob').put({name: 'bob', age: 24});
const carl = gun.get('person/carl').put({name: 'carl', age: 16});
const dave = gun.get('person/dave').put({name: 'dave', age: 42});

alice.on(function(node){
  console.log('Subscribed to Alice!', node);
});

console.log('==============', 'get Bob data');
gun.get('person/bob').val(function(node){
  console.log('Bob!', node);
});

const people = gun.get('people');
people.set(alice);
people.set(bob);
people.set(carl);
people.set(dave);

console.log('==============', 'get people data');
people.map().val(function (person) {
  console.log('The person is', person);
});

const company = gun.get('startup/hype').put({
  name: "hype",
  profitable: false,
  address: {
    street: "123 Hipster Lane",
    city: "San Francisco",
    state: "CA",
    country: "USA"
  }
});

console.log('==============');
company.val(function(startup){
  console.log("The startup:", startup);
});
company.get('address').get('city').val(function(value, key){
  console.log("What is the city?", value);
});
gun.get('startup/hype').put({ // or you could do `company.put({` instead.
  funded: true,
  address: {
    street: "999 Expensive Boulevard"
  }
});

const employees = company.get('employees');
employees.set(dave);
employees.set(alice);
employees.set(bob);

alice.get('spouse').put(bob);
bob.get('spouse').put(alice);

alice.get('spouse').get('employer').put(company);
alice.get('employer').put(company);

dave.get('kids').set(carl);
carl.get('dad').put(dave);

carl.get('friends').set(alice);
carl.get('friends').set(bob);

console.log('================', 'read related data');
gun.get('person/alice').get('spouse').get('employer').get('employees').map().get('name').val(function(data, key){
  console.log("The employee's", key, data);
});
```

Server code:
```
const Hapi  = require('hapi')
const Inert = require('inert')
const Gun   = require('gun')

const server = new Hapi.Server
server.connection({ port: 8080 })
server.connections.forEach(c => Gun({ web: c.listener, file: 'data.json' }))

server.register(Inert, () => {});

server.route({
  method: 'GET',
  path: '/gun.js',
  handler: (request, reply) => reply.file('./gun.js', { confine: false })
})

server.route({
  method: 'GET',
  path: '/{param*}',
  handler: {
    directory: {
      path: __dirname,
      redirectToSlash: true,
      index: true
    }
  }
})

server.start()
```

**Comment by d3x0r** [comment]
@amark 

For more info... this is because of this line
https://github.com/amark/gun/blob/master/lib/ws.js#L11

if there's no opt.web option then client websocket connections are not created.
Looked back through 0.8.0 and they all have the same problem.

**Comment by amark** [comment]
@sergibondarenko you confirmed @d3x0r 's patch got it working, right? So I'm gonna assume this is closed now. Please re-open if you need to!

👏 👏  @d3x0r for being so on top of it! 👏  👏

**Comment by BrockAtkinson** [comment]
I can access `http://localhost:3456` in my browser and see the result, plus `localhost:3456/gun` receives a message in my terminal using the following code:

```
const Hapi = require('hapi');
const Path = require('path');
const Gun = require('gun');

const server = Hapi.Server({
  port: 3456,
  host: 'localhost',
  routes: {
    files: { relativeTo: Path.join(__dirname, 'public') }
  }
});

var gun = Gun({ web: server });

function handle(req, h) {
  return '<h1>working hapi</h1>';
}

function serve() {
  console.log('serving gun');
  return Gun.serve;
}

const manifest = async function runtime() {
  
  server.route({ method: 'GET', path: '/', handler: handle });

  server.route({ method: 'GET', path: '/gun', handler: serve });

  await server.start();
  console.log('visit:', server.info.uri);
}

manifest();
```

Creates the following error message:
```
B:\www\test\node_modules\gun\node_modules\ultron\index.js:42
  this.ee.on(event, fn, context);
          ^

TypeError: this.ee.on is not a function
    at Ultron.on (B:\www\test\node_modules\gun\node_modules\ultron\index.
js:42:11)
    at new WebSocketServer (B:\www\test\node_modules\gun\node_modules\ws\
lib\WebSocketServer.js:84:20)
    at Object.mount [as next] (B:\www\test\node_modules\gun\lib\ws.js:21:
12)
    at Object.next (B:\www\test\node_modules\gun\lib\rs3.js:9:10)
    at Object.next (B:\www\test\node_modules\gun\lib\store.js:8:10)
    at Object.next (B:\www\test\node_modules\gun\nts.js:13:11)
    at Object.next (B:\www\test\node_modules\gun\gun.js:1705:12)
    at Function.onto [as on] (B:\www\test\node_modules\gun\gun.js:200:19)

    at Gun.chain.opt (B:\www\test\node_modules\gun\gun.js:811:9)
    at Function.Gun.create (B:\www\test\node_modules\gun\gun.js:682:22)
```

Am I doing something wrong?

**Comment by amark** [comment]
@BrockAtkinson I'm not sure, the error is crashing on `ultron` not `gun`, however, it may be how gun is calling it? The first gun code is `lib/ws`, however that line is calling `WebSocket.Server(ws)`.

I'm guessing this is because `Hapi` has a special `server` object that is not compatible with `ws` and NodeJS's `http` object. My guess is that `Hapi` probably exposes this somehow (it should be in the docs somewhere, like `server.httpServer` or something). It was a pain with `express` also.
