### ISSUE TITLE
Intermittent Issues with adding new peers via this.gun.opt({peers: []})

### ISSUE THREAD

**Issue by biosphere-labs** [amark/gun#535]
gun v0.9.996
```
.....\node_modules\ws\lib\websocket.js:143
    this._ultron.on('data', (data) => this._receiver.add(data));
                                                     ^

TypeError: Cannot read property 'add' of null
    at Socket._ultron.on (....\node_modules\ws\lib\websocket.js:143:54)
    at Socket.emit (events.js:185:15)
    at Socket.emit (domain.js:422:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
```
using
` this.gun.opt({peers: peers})` (nodejs GunServer)

Then getting a `gun.js:2024 WebSocket connection to 'ws://127.0.0.1:7667/gun' failed: Invalid frame header` which also seems replated. Happens on differrent peers, running on differrent peers all same code base. 

When this error isn't happening CAP theory is just looking like CRAP theory where peers randomly sync and sometimes don't. What I really wanna know is is it supposed to work? I didn't have these sort of issues when I was testing on a bridge network between VM peers. On a real local network it just doesn't seem to work. Any ideas?

**Comment by amark** [comment]
That error stack trace is coming from `ws` not from `gun` code.

Dynamically adding/changing peers right now with `gun.opt(peer)` currently does not have good tests behind it currently, and given that there is a known bug on peer reconnect, it is likely dynamically added peers have the same bug.

My guess this bug is happening because the `ws` adapter for GUN is attempting to call writes/listeners to that peer without that peer being in a proper readyState. So likely I'll be able to fix and mask/prevent this crash in gun with some if or trycatch, but this should also be reported to `ws` to be fixed as `_receiver` is one of their internal objects.

**Comment by fluidnotions** [comment]
Understood. Just out of interest I haven't really begun to understand the code, so perhaps you could tell me if pluging in an alternative transport for node.js peers would be feasible ? Websocket is the only option for the browser but for a node.js mesh on the backend there are many more sophisticated transports which already handle these sorts of issues .... discovery, heart beating, reconnection etc

**Comment by fluidnotions** [comment]
Also for this issue of Dynamically adding/changing peers right now with gun.opt(peer) currently not working, I tried killing and recreating the whole node.js http server instance, unformtunately server.close callback doesn't seem to happen. But assuming there is a way to do this kill the gun instance and recreating every time the peer list changes .... is this a viable short term solution for people who need dynamically changing peers?

**Comment by amark** [comment]
@fluidnotions you can look at the `lib/wire` code (which is pretty simple) to see how to write a different transport adapter. Although note that DAM (`mesh`) attempts itself to send messages on the standardized `wire` (the socket of whatever system), if other transports have different API interfaces, you'll need to provide a `peer.say = function(string){}` plugin in your adapter yourself that correctly calls whatever the actual command is.

Killing and restarting is something you can certainly try, IDK if it will cause (other) problems or not, but certainly worth experimenting with. Let me know how it goes.
