### ISSUE TITLE
.9.9994: store.js cannot read property of `on`

### ISSUE THREAD

**Issue by jadbox** [amark/gun#576]
In Gun 0.9.9994, this issue started happening in my Node.js build system:

```
    TypeError: Cannot read property 'on' of undefined

    > 1 | import * as Gun from 'gun'
        | ^
      2 | // const Gun = require('gun');
      3 | import { GunStorageProxy, LCState, VCState, Sig } from '../src/layer2storage'
      4 | require('gun/lib/then.js')

      at Object.<anonymous> (node_modules/gun/lib/store.js:5:5)
      at node_modules/gun/lib/server.js:12:2
      at Object.<anonymous> (node_modules/gun/lib/server.js:22:2)
      at Object.<anonymous> (node_modules/gun/index.js:1:45)
      at Object.<anonymous> (__tests__/base.gun.multi.spec.ts:1:1)
```

**Comment by amark** [comment]
Oye, should https://github.com/amark/gun/issues/571#event-1729523437 .
