### ISSUE TITLE
Gun in cordova app

### ISSUE THREAD

**Issue by mavericksthinker** [amark/gun#607]
Hello , I am currently working on a project where I have to build a cordova app that has a node server running on it. I was able to do that with the help of [nodejs for codova ](https://github.com/janeasystems/nodejs-mobile-cordova), I want to achieve this for cordova android app. Then the other aim is to sync the data on multiple clients which have a node server running in background. As I was using Gun database for the webserver to sync the data over multiple platform and also on cordova Android app(just client without any nodejs server), it worked perfectly fine (just with one issue I faced is that on my htc phone running the android app or on browser, the sync was very slow took like 1 to 2mins everytime, but other clients sync data instantaneously. kinda curious why is that happening ).
Coming back to the main issue when I run the same with nodejs running in the background of the client app , I faced two problems 
Let me provide the server code

                             const cordova = require('cordova-bridge');
                             var fs = require('fs');
                             var config = {
	                     port: process.env.OPENSHIFT_NODEJS_PORT || process.env.VCAP_APP_PORT || 
                             process.env.PORT || process.argv[2] || 8765
                             };
                             var Gun = require('gun');

                             if(process.env.HTTPS_KEY){
	                     config.key = fs.readFileSync(process.env.HTTPS_KEY);
	                     config.cert = fs.readFileSync(process.env.HTTPS_CERT);
	                     config.server = require('https').createServer(config, Gun.serve(__dirname));
                             } else {
	                     config.server = require('http').createServer(Gun.serve(__dirname));
                             }

                            var gun = Gun({
                              file:"./gun/server1",
                              web: config.server
                            });

                             config.server.listen(config.port);
                             console.log('Server started on port ' + config.port + ' with /gun');
                             // Handle the 'pause' and 'resume' events.
                             // These are events raised automatically when the app switched to the
                            // background/foreground.
                             cordova.app.on('pause', (pauseLock) => {
                             console.log('[node] app paused.');
                             pauseLock.release();
                             });

                             cordova.app.on('resume', () => {
                             console.log('[node] app resumed.');
                             cordova.channel.post('engine', 'resumed');
                             });
1.The   var gun = Gun({
                              file:"./gun/server1",
                              web: config.server
                            });
is providing the following error after I get this message on my android console

 I/NODEJS-MOBILE: Hello wonderful person! :) Thanks for using GUN, feel free to ask for help on https://gitter.im/amark/gun and ask StackOverflow questions tagged with 'gun'!

                     E/NODEJS-MOBILE: fs.js:892
                     return binding.mkdir(pathModule._makeLong(path),
                                  ^

                 Error: EROFS: read-only file system, mkdir '*'
                     at Object.fs.mkdirSync (fs.js:892:18)
                     at Store (/data/data/io.cordova.hellocordova/files/nodejs-mobile-cordova-assets/builtin_modules/gun/lib/rfs.js:34:35)
                     at Object.next (/data/data/io.cordova.hellocordova/files/nodejs-mobile-cordova-assets/builtin_modules/gun/lib/store.js:15:59)
                     at Function.onto [as on] (/data/data/io.cordova.hellocordova/files/nodejs-mobile-cordova-assets/builtin_modules/gun/gun.js:203:41)
                     at Function.Gun.create (/data/data/io.cordova.hellocordova/files/nodejs-mobile-cordova-assets/builtin_modules/gun/gun.js:692:10)
                     at new Gun (/data/data/io.cordova.hellocordova/files/nodejs-mobile-cordova-assets/builtin_modules/gun/gun.js:660:15)
                     at Gun (/data/data/io.cordova.hellocordova/files/nodejs-mobile-cordova-assets/builtin_modules/gun/gun.js:659:39)
                     at Object.<anonymous> (/data/data/io.cordova.hellocordova/files/www/nodejs-project/main.js:18:11)
                     at Module._compile (module.js:624:30)
                     at Object.Module._extensions..js (module.js:635:10)
                    D/MALI: osup_destructor:170: osup_destructor
                    D/Surface: Surface::disconnect(this=0xd0142500,api=1)
                    D/GraphicBuffer: unregister, handle(0xce4a5740) (w:600 h:1024 s:608 f:0x1 u:0x000b00)
                    D/GraphicBuffer: unregister, handle(0xce4a61c0) (w:600 h:1024 s:608 f:0x1 u:0x000b00)
                    W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
                    Chrome build fingerprint:
                    68.0.3440.91
                    344009152
                   ### ### ### ### ### ### ### ### ### ### ### ### ###
                    A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x24 in tid 10288 (RenderThread)
                    Application terminated.
As we can realize from the error its the directory location. I tried to create the directory in my server directory of the cordova android app, but it shows the same error.
so I tried to do this (storing the data in local storage)
var gun = Gun({
    file:"*",
    web: config.server,
     radisk: false,
    localStorage:true
});
This worked and the application worked but the problem is I was unable to sync the data between two clients as it is storing in their local storage. I need this app to sync like [INTENDED APPLICATION](https://www.youtube.com/channel/UCiSIpxlCqDXt--KUU0aE-KQ)(its for ios but I want to do that and android. 
Any help will be greatly appreciated.

**Comment by Dletta** [comment]
What storage adapter you use, is separate from the underlying sync protocol. Whether you use radisk or localStorage, should make no difference for syncing data between clients. What I don't see in your code, is how you specify a connection to the nodejs server, that allows your clients to sync. You would need to add: 
```
var gun = Gun({
file:"*",
web: config.server,
radisk: false,
localStorage:true,
peers: ['http://myPublicServerIPorUrl:port/gun'] //add this line
});
```

**Comment by mavericksthinker** [comment]
`<ul></ul>
            <script type="text/javascript" src="cordova.js"></script>
            <script type="text/javascript" src="js/index.js"></script>
            <script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/gun/gun.js"></script>
            <script>
				var gun = Gun('http://***.***.***.***:9876/gun).get('thoughts');
				$('form').on('submit', function(event){
					event.preventDefault();
					gun.set($('input').val());
					$('input').val("");
				});
				gun.map().on(function(thought, id){
					var li = $('#' + id).get(0) || $('<li>').attr('id', id).appendTo('ul');
					if(thought){
						$(li).text(thought);
					} else {
						$(li).hide();
					}
				});
				$('body').on('dblclick', 'li', function(event){
					gun.get(this.id).put(null);
				});
                     </script>
                     </body>
Please have a look I provide it here , which worked perfectly well for a n number of clients communicating with a single server which stores the data and does the sync seemlessly .But when it comes to each client has its own server which communicates among themselves as shown in the video , it causes problem. Also I just tried your way and the clients still dont sync.
Hope I can get a way to make this thing work via gun

**Comment by Dletta** [comment]
I think I understand now. 
You are trying to run a 'node.js' peer on the client. So other clients can connect to your client and download his data.

Now your second code runs as the app, but you said you had to save data in localStorage, because your OS doesn't allow you to write to disk from the 'Cordova Browser' you are running above code in, correct?

The node.js peer and the cordova app live in separate boxes, that don't sync data on your device. If your node code writes something using gun.get('something').put({name:'test'}), does the other client receive it?

If so, your problem is that your cordova app, needs to also connect to the node.js peer that is running locally on the phone, which then will initiate sync between what is in cordova and what is in node on your device, once that happens, the other client device will receive the syncs via the node.js.

Does that make sense?

**Comment by mavericksthinker** [comment]
Bull's-eye , that's what my aim is and you can see the require Cordova bridge in my nodejs code . That's what connects the client app(Cordova app ) to the nodejs app running in background to communicate.

**Comment by Dletta** [comment]
Hmm, one quirk that could be a cause, to establish the connection you also have to call gun.get('something').once((data)=>{return data;}), which opens the connection. 

But what you are describing, sounds like the node.js peer has no access to the android filesystem? Do the fs calls not work? 
According to your error ```Error: EROFS: read-only file system, mkdir '*'``` you have no write access for the node.js peer

**Comment by mavericksthinker** [comment]
It does as in my previous project as I mentioned , it is able to store the data. But in this when I specify the name of the directory or the data.json it is show not such directory found eventhough I made the directory myself and if i mention data.json ( which gets created automatically when i run the server on my laptop) it stills shows no such directories found.
The one you suggested I will try that and will be updating.

**Comment by Dletta** [comment]
I hope it works. I am shooting a bit in the dark with cordova.

**Comment by mavericksthinker** [comment]
Sadly It didnt work . Just wanted to ask if dgram is needed for sharing data between multiple peers on a local network or is there any defined way to do the same in gun

**Comment by mavericksthinker** [comment]
Sadly that dint work . But just wanted to ask , do we have to implement dgram to sync between multiple peers in local network or is there any way to do that via gun?

**Comment by amark** [comment]
oh no :(

@mavericksthinker I'm not smart enough to know so random guess: Would the browser WebRTC adapter help at all? I know internally WebRTC uses some UDP stuff, and I disabled WebRTC from using ordered/retried packets. I doubt it, but just a shot/chance.

**Comment by mavericksthinker** [comment]
Thank you for the idea will give it a try.
