### ISSUE TITLE
Gun/node Local Storage: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by TensorTom** [amark/gun#768]
The first time I run this: https://gist.github.com/TensorTom/0c6ff981f8f5183447cab4056e30064a it creates a directory `data` as I would expect. The second time I try to run it, I get:

```
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at Object.next (/home/user/public_html/test/superPeer/node_modules/gun/lib/file.js:19:6)
    at Object.next (/home/user/public_html/test/superPeer/node_modules/gun/lib/rs3.js:8:10)
    at Object.next (/home/user/public_html/test/superPeer/node_modules/gun/lib/store.js:5:13)
    at Function.onto [as on] (/home/user/public_html/test/superPeer/node_modules/gun/gun.js:197:41)
    at Function.Gun.create (/home/user/public_html/test/superPeer/node_modules/gun/gun.js:686:10)
    at new Gun (/home/user/public_html/test/superPeer/node_modules/gun/gun.js:654:15)
    at Gun (/home/user/public_html/test/superPeer/node_modules/gun/gun.js:653:39)
```
`data` directory permission is `775`, normal. Files within are `664`, also seems normal.

**Comment by TensorTom** [comment]
Just saw your Gitter. I have updated the Gist with the `AXE: false` (Though not relevant to this issue) and now it's running as requested. Here's what that looks like:

```
tensort@cyber1:~/public_html/test/superPeer$ rm -rf data/
tensort@cyber1:~/public_html/test/superPeer$ nohup node combo.js >combo.out 2>&1 &
[1] 9118
tensort@cyber1:~/public_html/test/superPeer$ tail -f combo.out
nohup: ignoring input
Hello wonderful person! :) Thanks for using GUN, feel free to ask for help on https://gitter.im/amark/gun and ask StackOverflow questions tagged with 'gun'!
AXE enabled.
WARNING! This `file.js` module for gun is intended for local development testing only!
AXE enabled.
ssl server listening on port: 8443
server listening on port: 8080
SSL Peers: http://localhost:8080/gun
Peers: https://tensortom.com:8443/gun
SSL Peers: http://localhost:8080/gun
Peers: https://tensortom.com:8443/gun
```

Notice I have to `rm -rf data/` before each run.

**Comment by amark** [comment]
@TensorTom ah, I think quickly:

Radisk uses `file: 'data'` and `file.js` (proxied as `localStorage`) is set to `true` and it also attempts to read/write from the `opt.file` property, but as a JSON file, while Radisk is operating on it as a folder.

Maybe good idea for this to be fixed/isolated/separated in future, but for now not high priority.

For now, don't use localStorage: true and radisk.

See if that fixes it? Or some combo thereof. Reopen if still issue.

**Comment by 34r7h** [comment]
Same error after copying the example from https://github.com/amark/gun/blob/master/examples/http.js
