### ISSUE TITLE
0.2019.711 and 0.2019.712  versions do not work on Windows

### ISSUE THREAD

**Issue by 3Dcube** [amark/gun#778]
Code:
```js
var Gun = require('gun');
var server = require('http').createServer().listen(8080);
var gun = Gun({web: server});
```
Output:
```
Hello wonderful person! :) Thanks for using GUN, feel free to ask for help on https://gitter.im/amark/gun and ask StackOverflow questions tagged with 'gun'!
C:\hello-gun\node_modules\gun\gun.js:69
                Type.obj = {is: function(o){ return o? (o instanceof Object && o.constructor === Object) || Object.prototype.toString.call(o).match(/^\[object (\w+)\]$/)[1] === 'Object' : false }}

                                       ^

RangeError: Maximum call stack size exceeded
    at String.match (<anonymous>)
    at is (C:\hello-gun\node_modules\gun\gun.js:69:129)
    at map (C:\hello-gun\node_modules\gun\gun.js:123:16)
    at Object.Type.obj.empty (C:\hello-gun\node_modules\gun\gun.js:106:12)
    at Object.each (C:\hello-gun\node_modules\gun\gun.js:844:48)
    at map (C:\hello-gun\node_modules\gun\gun.js:131:19)
    at Server.each (C:\hello-gun\node_modules\gun\gun.js:845:6)
    at map (C:\hello-gun\node_modules\gun\gun.js:131:19)
    at TCP.each (C:\hello-gun\node_modules\gun\gun.js:845:6)
    at map (C:\hello-gun\node_modules\gun\gun.js:142:18)
```
0.2019.627 works fine

**Comment by SunriseFox** [comment]
I tested on Windows 10 with node 12.6.0 and it does work normally... Maybe You could try to start a new project, `npm i gun` and try this code inside it to ensure it's not some issue related to node modules.

**Comment by 3Dcube** [comment]
It was a new project, but updating node.js fixed that.

**Comment by etamity** [comment]
@3Dcube  which node version are you using ?

**Comment by 3Dcube** [comment]
@etamity I'm sorry but I don't remember, it was some 10.* version, I updated to 10.16 and it works fine.
